# Generated by Django 4.1.5 on 2023-01-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Priduct',
            new_name='Product',
        ),
    ]
